In [1]:
pip install -U scikit-learn


     ---------------------------------------- 0.0/8.3 MB ? eta -:--:--
     - -------------------------------------- 0.3/8.3 MB 8.6 MB/s eta 0:00:01
     -- ------------------------------------- 0.6/8.3 MB 9.2 MB/s eta 0:00:01
     --- ------------------------------------ 0.7/8.3 MB 6.4 MB/s eta 0:00:02
     --- ------------------------------------ 0.8/8.3 MB 4.4 MB/s eta 0:00:02
     ---- ----------------------------------- 0.9/8.3 MB 4.2 MB/s eta 0:00:02
     ------ --------------------------------- 1.3/8.3 MB 4.8 MB/s eta 0:00:02
     -------- ------------------------------- 1.7/8.3 MB 5.5 MB/s eta 0:00:02
     ---------- ----------------------------- 2.2/8.3 MB 6.0 MB/s eta 0:00:02
     ------------- -------------------------- 2.8/8.3 MB 6.8 MB/s eta 0:00:01
     ---------------- ----------------------- 3.3/8.3 MB 7.5 MB/s eta 0:00:01
     ------------------- -------------------- 4.0/8.3 MB 7.9 MB/s eta 0:00:01
     --------------------- ------------------ 4.5/8.3 MB 8.2 MB/s eta 

In [2]:
pwd


'C:\\Users\\vaish\\OneDrive\\Desktop\\docs\\jupyter'

In [48]:
import pandas as pd
import numpy as nm
import matplotlib.pyplot as mtp

In [5]:
housing_dataset = pd.read_csv('C:/Users/vaish/OneDrive/Desktop/docs/jupyter/Housing.csv', sep=',', encoding='latin-1')

In [20]:
housing_dataset.head()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000  7420         4          2        3      yes        no       no   
1  12250000  8960         4          4        4      yes        no       no   
2  12250000  9960         3          2        2      yes        no      yes   
3  12215000  7500         4          2        2      yes        no      yes   
4  11410000  7420         4          1        2      yes       yes      yes   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished

In [6]:
housing_dataset.tail()

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
540  1820000  3000         2          1        1      yes        no      yes   
541  1767150  2400         3          1        1       no        no       no   
542  1750000  3620         2          1        1      yes        no       no   
543  1750000  2910         3          1        1       no        no       no   
544  1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished

In [24]:
print(housing_dataset.columns)

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')


In [31]:
housing_splitdata= housing_dataset.iloc[:, 0:5]
print(housing_splitdata)

        price  area  bedrooms  bathrooms  stories
0    13300000  7420         4          2        3
1    12250000  8960         4          4        4
2    12250000  9960         3          2        2
3    12215000  7500         4          2        2
4    11410000  7420         4          1        2
..        ...   ...       ...        ...      ...
540   1820000  3000         2          1        1
541   1767150  2400         3          1        1
542   1750000  3620         2          1        1
543   1750000  2910         3          1        1
544   1750000  3850         3          1        2

[545 rows x 5 columns]


In [52]:
X= housing_splitdata.iloc[:,1:]
print(X)

     area  bedrooms  bathrooms  stories
0    7420         4          2        3
1    8960         4          4        4
2    9960         3          2        2
3    7500         4          2        2
4    7420         4          1        2
..    ...       ...        ...      ...
540  3000         2          1        1
541  2400         3          1        1
542  3620         2          1        1
543  2910         3          1        1
544  3850         3          1        2

[545 rows x 4 columns]


In [35]:
Y= housing_splitdata.iloc[:,0]
print(Y)


0      13300000
1      12250000
2      12250000
3      12215000
4      11410000
         ...   
540     1820000
541     1767150
542     1750000
543     1750000
544     1750000
Name: price, Length: 545, dtype: int64


In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test= train_test_split( X,Y,test_size=0.25, random_state=0)

###### 

In [37]:
from sklearn.preprocessing import StandardScaler   
st_X= StandardScaler()  
X_train= st_X.fit_transform(X_train)    
X_test= st_X.transform(X_test)   

In [38]:
from sklearn.tree import DecisionTreeClassifier
classifier= DecisionTreeClassifier(criterion='entropy', random_state=0)
classifier.fit(X_train, Y_train) 

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [42]:
Y_pred= classifier.predict(X_test)
print(Y_pred)

[ 2653000  5250000  3360000  5600000  3500000  5600000  3430000  4193000
  4550000  7245000  6300000  2275000  4193000  5243000  6860000  1767150
  3493000  6860000  3010000  3570000  3773000  7700000  4620000  4340000
  6300000  2520000  4200000  2940000  2835000  6300000  2590000  4200000
  6090000  3423000  3220000  3990000  6629000  2485000  3395000  3850000
  8575000  8400000  9800000  4025000  4550000  6650000  4830000  3423000
  3990000  3675000  2450000  6790000  4340000  3255000  3500000  2940000
  8575000  4130000  3675000  8400000  7000000  9100000  3850000  5775000
  3220000  4200000  6300000  3570000  3570000  5740000  3850000  9800000
  3710000  5250000  6510000  4403000  3360000  6790000  2520000  3430000
  3850000  6895000  3570000  5215000  4130000  3010000  4193000  4200000
  2940000  3850000  6475000  8400000  3500000  3850000  2240000 10150000
  3850000  9100000  5320000  3087000  6790000  3360000  4200000  2485000
  8855000  5873000  5243000  3143000  5110000  3675

In [44]:
from sklearn.metrics import confusion_matrix  
cm= confusion_matrix(Y_test, Y_pred) 
print(cm)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]]


In [50]:
print(X_train, X_test)

[[-1.55021716 -1.35446064 -0.57931017  0.18542633]
 [ 0.09760377  0.06251357 -0.57931017 -0.94373698]
 [-1.05087748 -1.35446064 -0.57931017 -0.94373698]
 ...
 [ 0.32230663  0.06251357  1.47598157  2.44375293]
 [-0.75127368  0.06251357 -0.57931017 -0.94373698]
 [ 0.74674535  0.06251357 -0.57931017 -0.94373698]] [[-0.55153781  0.06251357 -0.57931017  0.18542633]
 [ 2.25475117  0.06251357 -0.57931017 -0.94373698]
 [-0.82118123  1.47948777 -0.57931017  0.18542633]
 [ 4.04238721 -1.35446064 -0.57931017 -0.94373698]
 [-0.7213133   1.47948777 -0.57931017  0.18542633]
 [ 0.62191043  0.06251357  1.47598157  1.31458963]
 [-0.62643876  0.06251357 -0.57931017 -0.94373698]
 [-0.81119444  0.06251357 -0.57931017  0.18542633]
 [-0.79521557 -1.35446064 -0.57931017 -0.94373698]
 [ 1.94516057  1.47948777  1.47598157  2.44375293]
 [ 0.44714155  1.47948777  1.47598157  2.44375293]
 [-0.57151139  0.06251357 -0.57931017  0.18542633]
 [-0.82617463  0.06251357 -0.57931017  0.18542633]
 [ 0.47710193  0.06251357

In [62]:
dt = DecisionTreeClassifier()

In [63]:
dt.fit(X_train, Y_train)

DecisionTreeClassifier()

In [64]:
Y_pred = dt.predict(X_test)

In [66]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_test, Y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.014598540145985401


In [67]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(X_test, X_pred)
print("Accuracy:", accuracy)

NameError: name 'X_pred' is not defined

In [68]:
#Prediction is done only for Y_set as the model is trained to predict the outcome from the training dataset.